defaults:
  - _self_
  - type@_here_: development

paths:
 datasets:
   root: dataset
   raw: ${.root}/raw
   processed: ${.root}/processed
   final: ${.root}/final
   local_db: ${.root}/local_db
debug: true
